### ISSUE TITLE
New span gets injected on every url change

### ISSUE THREAD

**Issue by eralpsahin** [eralpsahin/lynda-remaining-time#1]
Instead of updating the previously injected span, new spans get injected on remaining time calculation (on every url change). There should be only one injected span with the remaining time information.

![Screen Shot 2019-05-13 at 00 15 06](https://user-images.githubusercontent.com/10602289/57595624-2e69eb80-7514-11e9-9c94-193e16654ea3.png)

**Comment by atakanyenel** [comment]
https://github.com/eralpsahin/lynda-remaining-time/blob/75db8b0e0961a282cbf934abce36ddfe9d34cd48/main.js#L36

This line should check if a text node is already created.
